1、第一个练习题
Import the numpy package under the name np

In [1]:
import numpy as np

2、打印numpy的版本和配置说明
Print the numpy version and the configuration


In [2]:
print(np.__version__)
print(np.show_config())

1.26.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2628220032720
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.3
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.7
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


3、创建一个长度为10的空向量
Create a null vector of size 10

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4、如何找到任何一个数组的内存大小？
How to find the memory size of any array

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5、如何从命令行得到numpy中add函数的说明文档？
How to get the documentation of the numpy add function from the command line?

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6、创建一个长度为10并且除了第五个值为1的空向量
Create a null vector of size 10 but the fifth value which is 1

In [9]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7、创建一个值域范围从10到49的向量
Create a vector with values ranging from 10 to 49

In [10]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8、反转一个向量（第一个元素变为最后一个）
Reverse a vector (first element becomes last)

In [11]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9、创建一个 3x3 并且值从0到8的矩阵
Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
Z = np.arange(9).reshape(3,3)
print(Z)    

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10、找到数组[1,2,0,0,4,0]中非0元素的位置索引
Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11、创建一个 3x3 的单位矩阵
Create a 3x3 identity matrix

In [14]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
