1 导入numpy库并简写为 np (★☆☆)

In [ ]:
from numpy.lib import stride_tricks
import pandas as pd
import scipy.spatial as quick
import os
from numpy.lib.function_base import meshgrid
from numpy.core.function_base import linspace
import numpy as np

2 打印numpy的版本和配置说明 (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

3 创建一个长度为10的空向量 (★☆☆)  

In [ ]:
a = np.zeros(10)
print(a)

4 如何找到任何一个数据的内存大小？ (★☆☆)

In [ ]:
a = np.zeros((10,10))
print("%d bytes" % (a.size * a.itemsize))

5 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [ ]:
np.info(np.add)

6 创建一个第5个值为0的1向量 (★☆☆)

In [6]:
a = np.ones(10)
a[4] = 0
print(a)

[1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]


创建值域范围的数组

In [7]:
a = np.arange(10,30)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


反转数组

In [9]:
a=a[::-1]
print(a)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


查找非0元素位置的索引

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


创建一个3*3的矩阵，值域范围为[0,8]

In [13]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


创建一个3*3的单位矩阵

In [14]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


创建一个10*10*10的随机矩阵

In [16]:
a = np.random.random((3,3,3))
print(a)

[[[0.20170818 0.5871193  0.41232835]
  [0.06353393 0.49400797 0.53323372]
  [0.06640026 0.46008557 0.04781426]]

 [[0.25892463 0.70111037 0.30889453]
  [0.22065158 0.81405948 0.86938252]
  [0.2004803  0.25851068 0.09894242]]

 [[0.78050978 0.22135074 0.90855266]
  [0.97894038 0.77880752 0.26250661]
  [0.92936539 0.43550373 0.80200555]]]


创建一个10*10的数组，并找到最大值和最小值

In [17]:
a = np.random.random((10,10))
print(a)

[[0.50035125 0.00667535 0.31478801 0.90198937 0.60088156 0.50675071
  0.00663773 0.54854759 0.37538863 0.86196622]
 [0.3574234  0.22968757 0.04920989 0.60291774 0.21368744 0.17813105
  0.10120154 0.53937065 0.44183    0.26534003]
 [0.2060786  0.96003758 0.44790071 0.61383819 0.6429377  0.62038973
  0.41947772 0.53568855 0.734508   0.98614061]
 [0.18827213 0.13477628 0.37622046 0.28785335 0.32023497 0.06196957
  0.1923166  0.37018236 0.93830209 0.05276708]
 [0.39300547 0.26313265 0.35315063 0.71743256 0.82491756 0.62345595
  0.83237021 0.52909607 0.66214941 0.99368994]
 [0.05156655 0.10609248 0.88565005 0.47674273 0.06272408 0.79378264
  0.61003512 0.47885887 0.23997813 0.44811215]
 [0.12340334 0.89822829 0.59586939 0.28828567 0.32231501 0.3796251
  0.99949657 0.24683884 0.43805617 0.7727033 ]
 [0.50495777 0.28011802 0.96079482 0.56020887 0.46460411 0.48521311
  0.09638417 0.30035195 0.07421614 0.15423766]
 [0.15094146 0.82110422 0.18991241 0.87599282 0.1391718  0.24494269
  0.07621289 

In [18]:
a_min, a_max = a.min(), a.max()
print(a_min, a_max)

0.006637731512561973 0.9994965712147063


创建一个长度为30的随机向量，并找到它的平均值

In [20]:
a = np.random.random(30)
print(a)
Z_mean = a.mean()
print(Z_mean)

[0.70173261 0.67387139 0.0126511  0.77837683 0.70865652 0.10511389
 0.78179452 0.95091594 0.78372145 0.27416291 0.52139158 0.85562921
 0.39004657 0.7528484  0.37162241 0.56345697 0.36932559 0.11879262
 0.88485136 0.56214994 0.27821335 0.60275495 0.57481976 0.84793779
 0.44083208 0.7753302  0.78074445 0.43290074 0.65635405 0.1813007 ]
0.5577433294899901


创建一个二维数组，边界值为1，其余值为0

In [21]:
a = np.ones((10,10))
print(a)
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


对于一个存在数组，如何对边界添加0

In [22]:
a = np.ones((5,5))
print(a)
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


下面表达式运行的结果分别是什么
NaN= not a number,     Inf = infinity
表达式            结果
nan是什么意思
答：not a number

In [23]:
0* np.nan
np.nan==np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3*0.1

False

创建一个5*5的数组，并设置值1，2，3，4落在其对角线下方位置

In [24]:
a = np.diag(1+np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


创建一个8*8的矩阵，并且设置成棋盘样式

In [25]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


考虑一个(6,7,8)形状的数组，其第100个元素的索引(x,y,z)是什么？

In [26]:
Z=np.unravel_index(100,(6,7,8))
print(Z)

(1, 5, 4)


用tile函数去创建一个8*8的棋盘样式矩阵
tile(a,x):   x是控制a重复几次的，结果是一个一维数组
tile(a,(x,y))：   结果是一个二维矩阵，其中行数为x，列数是一维数组a的长度和y的乘积
tile(a,(x,y,z)):   结果是一个三维矩阵，其中矩阵的行数为x，矩阵的列数为y，而z表示矩阵每个单元格里a重复的次数。(三维矩阵可以看成一个二维矩阵，每个矩阵的单元格里存者一个一维矩阵a)
————————————————
版权声明：本文为CSDN博主「为爱存在」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/baiyu9821179/article/details/53364731

a = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

对于一个5*5的矩阵做归一化：(x-min)/(max-min)

In [28]:
a = np.random.random((5,5))
print(a)
a_max, a_min = a.max(), a.min()
a = (a-a_min)/(a_max-a_min)
print(a)

[[0.47365838 0.32534098 0.28587553 0.95194499 0.225451  ]
 [0.21970903 0.27052951 0.15469609 0.26805919 0.22778798]
 [0.46479108 0.9985299  0.44037702 0.20186506 0.47220429]
 [0.37541134 0.20505329 0.31075854 0.40072207 0.03854375]
 [0.83535208 0.73317773 0.96619541 0.33470253 0.16658284]]
[[0.45325094 0.29875142 0.25764099 0.95147335 0.19469786]
 [0.18871655 0.24165532 0.12099377 0.23908204 0.19713225]
 [0.44401404 1.         0.41858236 0.17012881 0.45173624]
 [0.3509088  0.17344994 0.28356116 0.37727453 0.        ]
 [0.83002065 0.72358751 0.96631775 0.30850318 0.13337598]]


创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

In [29]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\pc\AppData\Local\Temp\ipykernel_29372\223739713.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


一个5*3的矩阵与一个3*2的矩阵相乘，实矩阵乘积是什么
5*2的矩阵

In [30]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


给定一个一维数组，对其在3到8之间的所有元素取反

In [31]:
a = np.arange(11)
print(a)
a[(3<a)&(a<=8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


sum与np.sum的区别

In [34]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


考虑一个整数向量Z,下列表达合法的是哪个？
Z**Z    True
2 << Z >> 2  False      
Z <- Z  False
1j*Z  True  复数
Z/1/1  True
Z<Z>Z False

下列表达式的结果分别是什么？

In [36]:
np.array(0) / np.array(0)

C:\Users\pc\AppData\Local\Temp\ipykernel_29372\3272234849.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [37]:
np.array(0) // np.array(0)

C:\Users\pc\AppData\Local\Temp\ipykernel_29372\474058805.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [38]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\pc\AppData\Local\Temp\ipykernel_29372\3822400139.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

如何从零位对浮点数组做舍入 ?

In [40]:
a = np.random.uniform(-10,+10,10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))

[-9.85183369  4.91293425  5.96768996  7.01074246  3.40312235 -3.95045585
  4.19905364  1.45699997  0.58718751  8.744906  ]
[-10.   5.   6.   8.   4.  -4.   5.   2.   1.   9.]


如何找到两个数组中的共同元素?

In [41]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(a1)
print(a2)
print(np.intersect1d(a1,a2))

[1 6 5 5 1 7 2 1 3 5]
[5 6 3 3 4 2 1 0 8 2]
[1 2 3 5 6]


如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [42]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

Back to sanity

In [43]:
_ = np.seterr(**defaults)

另一个等价的方式，使用上下文管理器

In [44]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

下面的表达式是正确的吗?
np.sqrt(-1) == np.emath.sqrt(-1)

In [45]:
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Users\pc\AppData\Local\Temp\ipykernel_29372\3357785714.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

如何得到昨天，今天，明天的日期?

In [47]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2024-01-03
2024-01-04
2024-01-05


如何得到所有与2016年7月对应的日期？

In [48]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')  # 日期格式必须是这样的 2016-07    不能是2016-7   2016-07-01  2016-07-1   2016-7-01  2016-7-1 这些都不行   2016-07-01这种格式可以    2016-7-01这种格式不行  2016-07-1这种格式不行    2016-7-1这种格式不行  2016-07-01 00:00:00这种格式不行   2016-7-1 00:00:00这种格式不行 2016-07-01 00:00:00.000000这种格式不行  2016-7-1 00:00:00.000000这种格式不行    2016-07-01 00:00:00.000000000这种格式不行  2016-7-1 00:00:00.000000000这种格式不行  2016-07-01 00:00:00.00000000000000000
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


如何直接在位计算(A+B)\*(-A/2)(不建立中间变量)?

In [50]:
a = np.ones(3)*1
b = np.ones(3)*2
c = np.ones(3)*3
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
print(a)

[-1.5 -1.5 -1.5]


用五种不同的方法去提取一个随机数组的整数部分

In [51]:
a = np.random.uniform(0,10,10)
print(a)
print(a-a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[4.93432633 1.42843384 0.57426803 0.51489421 9.08396204 3.44892553
 2.28959692 3.67679066 2.91199421 6.87227594]
[4. 1. 0. 0. 9. 3. 2. 3. 2. 6.]
[4. 1. 0. 0. 9. 3. 2. 3. 2. 6.]
[4. 1. 0. 0. 9. 3. 2. 3. 2. 6.]
[4 1 0 0 9 3 2 3 2 6]
[4. 1. 0. 0. 9. 3. 2. 3. 2. 6.]


创建一个5*5的矩阵，其中每行的数值范围从0到4

In [52]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


如何用一个生成10个整数的函数来构建数组？

In [53]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


创建一个长度为10的向量，值域为0到1，不包括0和1

In [54]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


创建一个长度为10的随机向量，并排序

In [55]:
a=np.random.random(10)
a.sort()
print(a)

[0.06173743 0.31179363 0.31448625 0.34874775 0.4045858  0.63775893
 0.69014309 0.76472745 0.92201337 0.9763816 ]


对于一个小数组，如何用比 np.sum更快的方式对其求和？


In [56]:
a = np.arange(10)
np.add.reduce(a)


45

np.add.reduce是numpy.add模块中的一个函数，它的作用是对数组中的元素进行累加操作，即返回一个数组所有元素的和。


对于两个随机数组A和B，检查它们是否相等

In [57]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)

False


创建一个只读数组(read-only)

In [58]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

将笛卡尔坐标下的一个10*2的矩阵转换为极坐标形式


In [59]:
a = np.random.random((10,2))
x,y = a[:,0], a[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x) #arctan2(y,x)是求y/x的反正切值，返回值的范围是[-pi,pi]
print(r)
print(t)

[1.05670625 0.62901323 0.41732934 0.62129503 0.96190686 0.87853043
 0.6135099  0.98372528 1.17365459 0.69973345]
[0.62648885 0.60866067 1.53987258 0.69070185 1.17681426 0.46711373
 0.08918736 0.69032398 0.8860678  0.36560124]


创建一个长度为10的向量，并将向量中最大值替换为0

In [60]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.         0.08973939 0.46878546 0.69975978 0.70731401 0.61829126
 0.27613406 0.90673054 0.51439782 0.39424871]


创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域

In [61]:
a = np.zeros((5,5), [('x',float),('y',float)])
print(a)
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [62]:
x = np.arange(8)
y = x + 0.5
c= 1.0 / np.subtract.outer(x,y)
print(c)
print(np.linalg.det(c)) 

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.163637117973


打印每个numpy标量类型的最小值和最大值？

In [63]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


如何打印一个数组中的所有数值?

In [65]:
#np.set_printoptions(threshold=np.nan)
a = np.zeros((16,16))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


给定标量时，如何找到数组中最接近标量的值？

In [66]:
a = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(a-v)).argmin()
print(a[index])

25


思考形状如(100,2)的随机向量，求出点与点的距离
提示：np.atleast_2d, T, np.sqrt

In [67]:
a = np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.58040718 0.01307117 ... 0.60362801 0.6979324  0.5561549 ]
 [0.58040718 0.         0.57059013 ... 0.45335117 0.12950576 0.34496026]
 [0.01307117 0.57059013 0.         ... 0.59059071 0.68888173 0.54314843]
 ...
 [0.60362801 0.45335117 0.59059071 ... 0.         0.55535655 0.10902126]
 [0.6979324  0.12950576 0.68888173 ... 0.55535655 0.         0.45063233]
 [0.5561549  0.34496026 0.54314843 ... 0.10902126 0.45063233 0.        ]]


使用Scipy库更加快速的计算

In [68]:
import scipy.spatial

In [69]:
d = scipy.spatial.distance.cdist(a,a)
print(d)

[[0.         0.58040718 0.01307117 ... 0.60362801 0.6979324  0.5561549 ]
 [0.58040718 0.         0.57059013 ... 0.45335117 0.12950576 0.34496026]
 [0.01307117 0.57059013 0.         ... 0.59059071 0.68888173 0.54314843]
 ...
 [0.60362801 0.45335117 0.59059071 ... 0.         0.55535655 0.10902126]
 [0.6979324  0.12950576 0.68888173 ... 0.55535655 0.         0.45063233]
 [0.5561549  0.34496026 0.54314843 ... 0.10902126 0.45063233 0.        ]]


如何将一个32位的浮点数(float)转换为对应的整数(integer)?

In [70]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32, copy=False)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


如何读取以下文件？

In [71]:
z=np.genfromtxt("missing.dat",delimiter=",")
print(z)

FileNotFoundError: missing.dat not found.

numpy数组枚举(enumerate)的等价操作


In [72]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


构建一个二维高斯矩阵

In [73]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [74]:
n = 10
p = 3
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


减去矩阵的每一行的平均值

In [75]:
a = np.random.rand(5,10)
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)


[[0.26338731 0.23622101 0.57695199 0.09184217 0.90313369 0.85819234
  0.47095125 0.45741379 0.89211473 0.96104212]
 [0.13023307 0.06654531 0.66587835 0.18516286 0.3754644  0.67409687
  0.43701035 0.02305403 0.55894073 0.9867623 ]
 [0.34858837 0.28801508 0.2068467  0.35958091 0.53655795 0.47128115
  0.44473514 0.87244761 0.37413125 0.52207328]
 [0.74590967 0.29765538 0.84095336 0.62781406 0.24971307 0.30984629
  0.59882228 0.86652926 0.61010653 0.00261766]
 [0.13380832 0.52977199 0.49251369 0.65003703 0.87540015 0.63687526
  0.26975556 0.61631935 0.91132478 0.54833116]]
[[-0.30773773 -0.33490403  0.00582695 -0.47928287  0.33200865  0.2870673
  -0.10017379 -0.11371125  0.32098969  0.38991708]
 [-0.28008176 -0.34376952  0.25556352 -0.22515197 -0.03485043  0.26378204
   0.02669552 -0.38726079  0.14862591  0.57644747]
 [-0.09383737 -0.15441067 -0.23557904 -0.08284483  0.0941322   0.02885541
   0.0023094   0.43002187 -0.0682945   0.07964753]
 [ 0.23091292 -0.21734138  0.3259566   0.1128173  

如何判断一个给定的数组存在空列

In [76]:
a = np.random.randint(0,3,(3,10))
print(a)
print((~a.any(axis=0)).any())

[[1 0 1 0 2 1 0 2 1 2]
 [1 0 1 1 2 1 0 1 0 1]
 [0 2 2 0 0 2 0 1 0 2]]
True


从数组中找出与给定值最接近的数

In [77]:
a = np.random.uniform(0,1,10)
print(a)
z = 0.5
m = a.flat[np.abs(a-z).argmin()]
print(m)

[0.76784085 0.39048636 0.63850753 0.69966853 0.23306617 0.8683204
 0.94935101 0.72347011 0.00317349 0.63855921]
0.3904863626430618


形状如(1,3)和(3,1)的两个数组，如何使用迭代器计算它们的和？

In [79]:
a = np.arange(3).reshape(3,1)
print(a)
b = np.arange(3).reshape(1,3)
print(b)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x+y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


创建一个具有name属性的数组类

In [80]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z_named = NamedArray(np.arange(10), "range_10")
print(Z_named.name)

range_10


给定一个向量，如何让在第二个向量索引的每个元素加1(小心重复的索引)?
用b中数据去当中a的索引，然后a中对应的索引的值加1
创建一个包含20个在0（包括）到 'a' 的长度（不包括）之间的随机整数的数组 'b'
b = np.random.randint(0, len(a), 20)

np.bincount(b, minlength=len(a)) 函数计算 'b' 中每个值的出现次数，并递增 'a' 中相应的元素。minlength=len(a) 参数确保生成的 bincount 数组具有与 'a' 相同的长度。

步骤:
1、计算b中每个值的出现次数，返回一个数组，数组的长度为b中出现所有元素个数，数组中的每个元素的值为b中对应索引的值出现的次数
 2、将a中对应索引的值加上b中出现的次数数组，返回一个新的数组
 3、再将a数组做一次b数组的元素当做索引对索引元素加1

In [83]:
a = np.ones(10)
print(a)
b = np.random.randint(0,len(a),20)
print(b)
a += np.bincount(b, minlength=len(a))
print(a)
np.add.at(a, b, 1)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 2 1 4 1 1 6 7 9 9 0 0 9 9 7 1 0 1 9 3]
[4. 7. 2. 2. 2. 1. 2. 3. 1. 6.]
[ 7. 13.  3.  3.  3.  1.  3.  5.  1. 11.]


如果根据索引列表I将向量X的元素累加到数组F中，那么重复的索引元素在F中对应位置的值该如何计算？


In [90]:
x = [1,3,3,3,5,6]
i = [1,3,9,3,4,1]
k = np.bincount(i)
#数组I长度中各个数据重复值，将重复值带入X（类似各个数据节点对应权值）中相加为结果
print(k)

[0 2 0 2 1 0 0 0 0 1]


有大问题
np.bincoun(i,x)  i是索引数组，x是权值数组，返回一个数组，数组的索引表示i中的值，数组的值表示相应索引位置上值的加权和

在数组 i 中，最大的值是 9，因此 np.bincount 将结果数组的长度设置为 10（最大值加 1）。在结果数组中，索引 9 对应的值是 i 数组中值为 9 的权值之和。
对于索引 9：

在数组 i 中，值 9 出现了一次。
在 x 数组中，与值 9 对应的权值是 0（因为在 x 中没有值为 9 的元素）。
因此，索引 9 对应的值是 x 数组中值为 9 的权值之和，结果是 0。
  

np.bincount(i, weights=x) 根据数组 i 中每个值的出现次数计算了数组 x 中每个值的加权和。输出是一个数组，其中每个索引表示数组 i 中的唯一值，相应的值是该值的加权和。

i 数组中的每个元素在 x 数组中都有一个相应的权值。在输出数组中：

索引 0 对应的值是 0，因为 0 在 i 中没有出现。
索引 1 对应的值是 7，因为 1 在 i 中出现了两次，对应的权值是 x 中的 1 和 6 的和。
索引 2 对应的值是 0，因为 2 在 i 中没有出现。
索引 3 对应的值是 6，因为 3 在 i 中出现了三次，对应的权值是 x 中的 3 + 3 + 3 的和。
索引 4 对应的值是 5，因为 4 在 i 中出现了一次，对应的权值是 x 中的 5。
索引 5 对应的值是 0，因为 5 在 i 中没有出现。
索引 6 对应的值是 0，因为 6 在 i 中没有出现。
索引 7 对应的值是 0，因为 7 在 i 中没有出现。
索引 8 对应的值是 0，因为 8 在 i 中没有出现。
索引 9 对应的值是 3，因为 9 在 i 中出现了一次，对应的权值是 x 中的 3。
np.bincount(arr) 统计了 arr 中每个值的出现次数，并返回一个数组，数组的索引表示值，数组的值表示相应索引位置上值的出现次数。
arr 是索引数组，weights 是权值数组。np.bincount(arr, weights=weights) 返回一个数组，数组的索引表示 arr 中的值，数组的值表示相应索引位置上值的加权和


思考(dtype=ubyte)的(w,h,3)图像，计算唯一颜色的数量

In [91]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 + I[...,2]
n = len(np.unique(F))
print(n) 


4


这段代码使用 NumPy 创建了一个形状为 (16, 16, 3) 的三维数组 I，其中的元素都是在 [0, 2) 范围内的随机整数，并将其转换为 np.ubyte 类型。接着，通过将 RGB 值合并成一个整数数组 F，使用唯一函数 np.unique 计算唯一值的数量，最后打印出结果。

w 和 h 被设置为 16。
np.random.randint(0, 2, (h, w, 3)) 创建一个形状为 (16, 16, 3) 的三维数组 I，元素为 [0, 2) 范围内的随机整数。
I.astype(np.ubyte) 将数组 I 中的元素类型转换为 np.ubyte。
I[..., 0] * 256 * 256 + I[..., 1] * 256 + I[..., 2] 将 RGB 值合并为一个整数数组 F。
np.unique(F) 计算 F 中的唯一值。
len(np.unique(F)) 返回唯一值的数量。
print(n) 打印结果。
这段代码的目的是统计形状为 (16, 16, 3) 的随机 RGB 图像中不同颜色的数量。每个颜色通过 RGB 值合并成一个唯一的整数值，然后使用 np.unique 统计不同颜色的数量。



考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？

In [92]:
a = np.random.randint(0,10,(3,4,3,4))
print(a)
sum = a.sum(axis=(-2,-1))
print(sum)

[[[[4 1 8 8]
   [3 4 4 1]
   [0 1 8 2]]

  [[2 2 9 0]
   [2 4 5 3]
   [8 3 3 1]]

  [[8 7 8 9]
   [9 7 6 7]
   [3 4 6 7]]

  [[9 0 1 7]
   [8 7 3 6]
   [6 7 7 9]]]


 [[[8 1 9 2]
   [1 4 9 9]
   [6 5 9 8]]

  [[7 3 5 8]
   [7 6 3 5]
   [5 7 9 5]]

  [[1 6 5 8]
   [8 2 4 0]
   [1 4 9 6]]

  [[6 5 7 6]
   [0 9 5 2]
   [0 6 3 3]]]


 [[[8 8 6 2]
   [7 5 6 6]
   [8 0 4 9]]

  [[3 2 3 6]
   [2 7 8 6]
   [5 6 5 5]]

  [[7 2 2 9]
   [2 7 5 0]
   [6 5 6 7]]

  [[8 5 3 0]
   [0 9 2 2]
   [3 1 3 4]]]]
[[44 42 81 70]
 [71 70 54 52]
 [69 58 58 40]]


方法2

In [93]:
a=np.random.randint(0,10,(3,4,3,4))
print(a)
sum=a.reshape(a.shape[:-2]+(-1,)).sum(axis=-1)
print(sum)

[[[[0 7 7 7]
   [6 9 7 0]
   [6 2 5 7]]

  [[5 4 5 0]
   [1 3 8 1]
   [9 6 1 5]]

  [[3 0 8 9]
   [6 6 9 9]
   [7 4 1 3]]

  [[7 3 8 7]
   [9 8 6 0]
   [0 6 8 8]]]


 [[[9 3 9 5]
   [3 3 1 9]
   [7 8 4 1]]

  [[5 9 7 0]
   [4 1 5 9]
   [4 4 9 9]]

  [[6 3 2 7]
   [3 2 4 2]
   [8 7 7 3]]

  [[1 5 2 8]
   [6 4 3 3]
   [5 3 9 3]]]


 [[[0 9 9 3]
   [1 9 5 7]
   [3 7 7 2]]

  [[7 1 5 9]
   [4 9 7 8]
   [7 2 7 8]]

  [[9 8 2 4]
   [6 5 7 3]
   [2 9 8 3]]

  [[3 4 5 8]
   [5 2 5 9]
   [3 3 3 6]]]]
[[63 48 65 70]
 [62 66 54 52]
 [62 74 66 56]]


给定一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

In [95]:
D = np.random.uniform(0,1,100)
print(D)
S = np.random.randint(0,10,100)
print(S)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
#方法2
print(pd.Series(D).groupby(S).mean())

[0.59887475 0.58775928 0.05201602 0.40960809 0.46518719 0.98297601
 0.70460973 0.676317   0.54283017 0.90193415 0.96481811 0.11811483
 0.72561377 0.64965735 0.5976504  0.64880491 0.85964552 0.58503795
 0.56925072 0.01762537 0.70780617 0.3696122  0.37018385 0.24069308
 0.40977196 0.00872037 0.6752106  0.7241624  0.79593596 0.35345221
 0.02029482 0.33635009 0.455654   0.33366714 0.16332045 0.71080987
 0.00980551 0.63489101 0.09425299 0.62114747 0.06981277 0.87723212
 0.25473821 0.48126954 0.08605844 0.58271918 0.95087667 0.99962603
 0.31384042 0.56557102 0.33026526 0.05516266 0.31399704 0.21551595
 0.60065913 0.37364494 0.73702028 0.32100597 0.98174768 0.20387893
 0.7997739  0.90580614 0.88187318 0.82521889 0.15082444 0.65340445
 0.80642635 0.71450336 0.70688295 0.08300227 0.55055926 0.70350294
 0.15543053 0.9025046  0.53701505 0.07165357 0.75609079 0.22362829
 0.84931553 0.96745577 0.59534811 0.76364018 0.03639016 0.54522614
 0.63469845 0.39984626 0.4918844  0.32003815 0.88508248 0.4767

np.bincount 函数的功能是统计非负整数数组中每个值的出现次数，并可选择使用权重进行计数。在这里，它的目的是根据索引或类别数组 S 中的值，计算对应权重数组 D 中的权重的和。
如果 weights 参数被指定，那么 x 会被它加权。如果值 n 发现在位置 i，那么out[n] += weight[i]而非out[n] += 1。因此，我们 weights 的大小必须与 x 相同，否则报错。


如何获得点积dot prodcut的对角线？


In [100]:
a = np.random.uniform(0,1,(5,5))
print(a)
b = np.random.uniform(0,1,(5,5))
print(b)
c=np.dot(a,b)
w= np.diag(c)
print(c)
print(w)
#方法2
print(np.sum(a*b.T, axis=1))
#方法3
print(np.einsum("ij,ji->i", a, b))

[[0.57565914 0.29399829 0.79190621 0.15938087 0.66727504]
 [0.10601962 0.72310491 0.95182918 0.68503664 0.70327697]
 [0.11268061 0.68370836 0.31239236 0.31370604 0.18118785]
 [0.28819625 0.0927227  0.93746056 0.37404491 0.55383491]
 [0.01488355 0.80017629 0.14691364 0.58039877 0.01247   ]]
[[0.85066128 0.94969357 0.66697879 0.46070321 0.47285245]
 [0.47995001 0.46670899 0.28732915 0.09221064 0.04748191]
 [0.84019942 0.44407431 0.16868539 0.69833511 0.47518124]
 [0.82444003 0.75033833 0.36472398 0.75472772 0.08734695]
 [0.83304529 0.51367772 0.19126881 0.08426043 0.90532102]]
[[1.98342487 1.49793054 0.78776866 1.02184774 1.28047996]
 [2.38760051 1.73611556 0.82340587 1.35649184 1.23328469]
 [1.09604025 0.89328814 0.47337265 0.58514167 0.4256225 ]
 [1.84706064 1.29842769 0.61935312 1.12495301 1.12021069]
 [1.00903429 0.89472587 0.47869364 0.62233039 0.17682765]]
[1.98342487 1.73611556 0.47337265 1.12495301 0.17682765]
[1.98342487 1.73611556 0.47337265 1.12495301 0.17682765]
[1.98342487 1

a*b.T表示对应的角标相乘，每行和恰好是AB的dot叉乘的和

考虑一个向量【1，2，3，4，5】，如何建立一个新的向量，在这个新的向量中每个值之间有3个连续的零（array[::4]）

In [101]:
a = np.array([1,2,3,4,5])#np.arange(1,6)
nz=3
a0 = np.zeros(len(a)+(len(a)-1)*(nz))
a0[::nz+1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


考虑一个维度（5,5,3）的数组，如何将其与一个（5,5）的数组相乘？

In [102]:
a = np.ones((5,5,3))
print(a)
b = 2*np.ones((5,5))
print(b)
print(a*b[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


在这个例子中，array_2d[:, :, np.newaxis] 将二维数组 array_2d 扩展为形状 (5, 5, 1)，以便与形状为 (5, 5, 3) 的三维数组 array_3d 进行广播。然后，逐元素相乘产生一个形状为 (5, 5, 3) 的结果数组 result。
关键在于使用 np.newaxis 或 None 来插入一个新的轴，以便广播可以正确进行。在上述示例中，array_2d[:, :, np.newaxis] 在数组 array_2d 的最后一个轴后插入了一个新的轴。

如何对一个数组中任意两行做交换？

In [103]:
a = np.arange(25).reshape(5,5)
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment
numpy.roll(a,shift,axis=None)沿着给定轴滚动数组元素。超出最后位置的元素将会回滚到第一个位置
将a沿着axis方向滚动shift长度 a:输入数组 shift：滚动长度（若为元组则轴也为元组） 
axis：滚动轴 0为垂直滚动，1为水平滚动（若为None则数组在移位前扁平化，之后恢复原状）
输出与a维度一致

numpy.repaet(a,num,axis=None)沿着给定轴复制数组元素num次，会增加原数组维度
axis=None：扁平化，每个元素复制num次
axis=0：沿着列方向复制，每行元素复制num次
axis=1：沿着行方向复制，每列元素复制num次

numpy.ndarray.view函数对内存区域不同的切割方式，来完成数据类型的转换，无需对数据进行额外的copy
但内存需要连续

a,b,c = numpy.unique(A,return_index=True,return_inverse=True)函数取出原数组中重复元素，并按照元素由大到小返回新元组或列表
a:无重复元素的新数组
b：新数组元素在原数组中位置
c：旧数组元素在新数组中位置
————————————————
版权声明：本文为CSDN博主「Abel Alan」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/weixin_39922926/article/details/120316867

In [105]:
faces = np.random.randint(0,100,(10,3))
print(faces)

[[62 58 40]
 [47 96 20]
 [99 93 85]
 [25  9 51]
 [78 61 99]
 [83 87 51]
 [86 99 41]
 [30 58 49]
 [75 80 54]
 [31 23 28]]


In [106]:
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3, 2)

In [107]:
"""
np.sort函数：按照行进行排序
axis=0：按照列进行排序
axis=1：按照行进行排序
默认按照行进行排序
"""
F = np.sort(F, axis=1)
"""
view函数用法
"""
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
D = np.unique(G)
print(G)

[[(58, 62)]
 [(40, 58)]
 [(40, 62)]
 [(47, 96)]
 [(20, 96)]
 [(20, 47)]
 [(93, 99)]
 [(85, 93)]
 [(85, 99)]
 [( 9, 25)]
 [( 9, 51)]
 [(25, 51)]
 [(61, 78)]
 [(61, 99)]
 [(78, 99)]
 [(83, 87)]
 [(51, 87)]
 [(51, 83)]
 [(86, 99)]
 [(41, 99)]
 [(41, 86)]
 [(30, 58)]
 [(49, 58)]
 [(30, 49)]
 [(75, 80)]
 [(54, 80)]
 [(54, 75)]
 [(23, 31)]
 [(23, 28)]
 [(28, 31)]]


给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C

In [108]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


如何通过滑动窗口计算一个数组的平均数？
np.cumsum(a, axis=None, dtype=None, out=None)函数返回给定轴上的元素的累积和

In [109]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret)
    return ret[n-1:]/n
Z = np.arange(20)
print(moving_average(Z, n=3))

[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[ 0.  1.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48.
 51. 54.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


np.cumsum(a, dtype=float): 使用 np.cumsum 计算数组 a 的累积和，并将结果保存在 ret 中。这个操作会生成一个新的数组，其中的每个元素是原数组对应位置及之前所有元素的累积和。

ret[n:] = ret[n:] - ret[:-n]: 使用广播（broadcasting）计算移动窗口内的和。ret[n:] 是从索引 n 开始的部分，ret[:-n] 是从索引 0 到 n-1 的部分。这一步将后面的部分减去前面的部分，得到了每个窗口内的和。

return ret[n-1:]/n: 返回计算好的移动平均值，从索引 n-1 开始，因为在前面的计算中，窗口大小为 n 的和从这个位置开始。最后除以窗口大小 n 得到平均值。

这个函数的实际效果是计算了输入数组 Z 的移动平均值，窗口大小为3。在实际应用中，移动平均常用于平滑时间序列数据，以减小噪音和突发的影响。

思考一维数组Z，构建一个二维数组，其第一行是（Z[0],Z[1],Z[2]），然后每一行移动一位，最后一行为（Z[-3],Z[-2],Z[-1]）提示：from numpy.lib import stride_tricks


In [110]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10, dtype=np.int8), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


shape = (a.size - window + 1, window): 计算新数组的形状，新数组将包含 (a.size - window + 1) 行和 window 列。

strides = (a.itemsize, a.itemsize): 计算新数组的步幅，这里设置为 (a.itemsize, a.itemsize)，表示在原数组中按照元素的字节大小进行移动。

stride_tricks.as_strided(a, shape=shape, strides=strides): 使用 as_strided 函数创建一个新数组，该数组的形状和步幅由前面计算得到。这样做是为了实现一个滚动视窗的效果，而不实际复制数组的数据。as_strided 函数允许创建基于原始数据的视图。