1 导入numpy库并简写为 np (★☆☆)

In [ ]:
from numpy.lib import stride_tricks
import pandas as pd
import scipy.spatial as quick
import os
from numpy.lib.function_base import meshgrid
from numpy.core.function_base import linspace
import numpy as np

2 打印numpy的版本和配置说明 (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

3 创建一个长度为10的空向量 (★☆☆)  

In [ ]:
a = np.zeros(10)
print(a)

4 如何找到任何一个数据的内存大小？ (★☆☆)

In [ ]:
a = np.zeros((10,10))
print("%d bytes" % (a.size * a.itemsize))

5 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [ ]:
np.info(np.add)

6 创建一个第5个值为0的1向量 (★☆☆)

In [6]:
a = np.ones(10)
a[4] = 0
print(a)

[1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]


创建值域范围的数组

In [7]:
a = np.arange(10,30)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


反转数组

In [9]:
a=a[::-1]
print(a)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
