1 导入numpy库并简写为 np (★☆☆)

In [ ]:
from numpy.lib import stride_tricks
import pandas as pd
import scipy.spatial as quick
import os
from numpy.lib.function_base import meshgrid
from numpy.core.function_base import linspace
import numpy as np

2 打印numpy的版本和配置说明 (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

3 创建一个长度为10的空向量 (★☆☆)  

In [ ]:
a = np.zeros(10)
print(a)

4 如何找到任何一个数据的内存大小？ (★☆☆)

In [ ]:
a = np.zeros((10,10))
print("%d bytes" % (a.size * a.itemsize))

5 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [ ]:
np.info(np.add)

6 创建一个第5个值为0的1向量 (★☆☆)

In [6]:
a = np.ones(10)
a[4] = 0
print(a)

[1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]


创建值域范围的数组

In [7]:
a = np.arange(10,30)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


反转数组

In [9]:
a=a[::-1]
print(a)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


查找非0元素位置的索引

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


创建一个3*3的矩阵，值域范围为[0,8]

In [13]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


创建一个3*3的单位矩阵

In [14]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


创建一个10*10*10的随机矩阵

In [16]:
a = np.random.random((3,3,3))
print(a)

[[[0.20170818 0.5871193  0.41232835]
  [0.06353393 0.49400797 0.53323372]
  [0.06640026 0.46008557 0.04781426]]

 [[0.25892463 0.70111037 0.30889453]
  [0.22065158 0.81405948 0.86938252]
  [0.2004803  0.25851068 0.09894242]]

 [[0.78050978 0.22135074 0.90855266]
  [0.97894038 0.77880752 0.26250661]
  [0.92936539 0.43550373 0.80200555]]]


创建一个10*10的数组，并找到最大值和最小值

In [17]:
a = np.random.random((10,10))
print(a)

[[0.50035125 0.00667535 0.31478801 0.90198937 0.60088156 0.50675071
  0.00663773 0.54854759 0.37538863 0.86196622]
 [0.3574234  0.22968757 0.04920989 0.60291774 0.21368744 0.17813105
  0.10120154 0.53937065 0.44183    0.26534003]
 [0.2060786  0.96003758 0.44790071 0.61383819 0.6429377  0.62038973
  0.41947772 0.53568855 0.734508   0.98614061]
 [0.18827213 0.13477628 0.37622046 0.28785335 0.32023497 0.06196957
  0.1923166  0.37018236 0.93830209 0.05276708]
 [0.39300547 0.26313265 0.35315063 0.71743256 0.82491756 0.62345595
  0.83237021 0.52909607 0.66214941 0.99368994]
 [0.05156655 0.10609248 0.88565005 0.47674273 0.06272408 0.79378264
  0.61003512 0.47885887 0.23997813 0.44811215]
 [0.12340334 0.89822829 0.59586939 0.28828567 0.32231501 0.3796251
  0.99949657 0.24683884 0.43805617 0.7727033 ]
 [0.50495777 0.28011802 0.96079482 0.56020887 0.46460411 0.48521311
  0.09638417 0.30035195 0.07421614 0.15423766]
 [0.15094146 0.82110422 0.18991241 0.87599282 0.1391718  0.24494269
  0.07621289 

In [18]:
a_min, a_max = a.min(), a.max()
print(a_min, a_max)

0.006637731512561973 0.9994965712147063


创建一个长度为30的随机向量，并找到它的平均值

In [20]:
a = np.random.random(30)
print(a)
Z_mean = a.mean()
print(Z_mean)

[0.70173261 0.67387139 0.0126511  0.77837683 0.70865652 0.10511389
 0.78179452 0.95091594 0.78372145 0.27416291 0.52139158 0.85562921
 0.39004657 0.7528484  0.37162241 0.56345697 0.36932559 0.11879262
 0.88485136 0.56214994 0.27821335 0.60275495 0.57481976 0.84793779
 0.44083208 0.7753302  0.78074445 0.43290074 0.65635405 0.1813007 ]
0.5577433294899901


创建一个二维数组，边界值为1，其余值为0

In [21]:
a = np.ones((10,10))
print(a)
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


对于一个存在数组，如何对边界添加0

In [22]:
a = np.ones((5,5))
print(a)
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


下面表达式运行的结果分别是什么
NaN= not a number,     Inf = infinity
表达式            结果
nan是什么意思
答：not a number

In [23]:
0* np.nan
np.nan==np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3*0.1

False

创建一个5*5的数组，并设置值1，2，3，4落在其对角线下方位置

In [24]:
a = np.diag(1+np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


创建一个8*8的矩阵，并且设置成棋盘样式

In [25]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


考虑一个(6,7,8)形状的数组，其第100个元素的索引(x,y,z)是什么？

In [26]:
Z=np.unravel_index(100,(6,7,8))
print(Z)

(1, 5, 4)


用tile函数去创建一个8*8的棋盘样式矩阵
tile(a,x):   x是控制a重复几次的，结果是一个一维数组
tile(a,(x,y))：   结果是一个二维矩阵，其中行数为x，列数是一维数组a的长度和y的乘积
tile(a,(x,y,z)):   结果是一个三维矩阵，其中矩阵的行数为x，矩阵的列数为y，而z表示矩阵每个单元格里a重复的次数。(三维矩阵可以看成一个二维矩阵，每个矩阵的单元格里存者一个一维矩阵a)
————————————————
版权声明：本文为CSDN博主「为爱存在」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/baiyu9821179/article/details/53364731

a = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

对于一个5*5的矩阵做归一化：(x-min)/(max-min)

In [28]:
a = np.random.random((5,5))
print(a)
a_max, a_min = a.max(), a.min()
a = (a-a_min)/(a_max-a_min)
print(a)

[[0.47365838 0.32534098 0.28587553 0.95194499 0.225451  ]
 [0.21970903 0.27052951 0.15469609 0.26805919 0.22778798]
 [0.46479108 0.9985299  0.44037702 0.20186506 0.47220429]
 [0.37541134 0.20505329 0.31075854 0.40072207 0.03854375]
 [0.83535208 0.73317773 0.96619541 0.33470253 0.16658284]]
[[0.45325094 0.29875142 0.25764099 0.95147335 0.19469786]
 [0.18871655 0.24165532 0.12099377 0.23908204 0.19713225]
 [0.44401404 1.         0.41858236 0.17012881 0.45173624]
 [0.3509088  0.17344994 0.28356116 0.37727453 0.        ]
 [0.83002065 0.72358751 0.96631775 0.30850318 0.13337598]]


创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

In [29]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\pc\AppData\Local\Temp\ipykernel_29372\223739713.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


一个5*3的矩阵与一个3*2的矩阵相乘，实矩阵乘积是什么
5*2的矩阵

In [30]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


给定一个一维数组，对其在3到8之间的所有元素取反

In [31]:
a = np.arange(11)
print(a)
a[(3<a)&(a<=8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


sum与np.sum的区别

In [34]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


考虑一个整数向量Z,下列表达合法的是哪个？
Z**Z    True
2 << Z >> 2  False      
Z <- Z  False
1j*Z  True  复数
Z/1/1  True
Z<Z>Z False

下列表达式的结果分别是什么？

In [36]:
np.array(0) / np.array(0)

C:\Users\pc\AppData\Local\Temp\ipykernel_29372\3272234849.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [37]:
np.array(0) // np.array(0)

C:\Users\pc\AppData\Local\Temp\ipykernel_29372\474058805.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [38]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\pc\AppData\Local\Temp\ipykernel_29372\3822400139.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

如何从零位对浮点数组做舍入 ?

In [40]:
a = np.random.uniform(-10,+10,10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))

[-9.85183369  4.91293425  5.96768996  7.01074246  3.40312235 -3.95045585
  4.19905364  1.45699997  0.58718751  8.744906  ]
[-10.   5.   6.   8.   4.  -4.   5.   2.   1.   9.]


如何找到两个数组中的共同元素?

In [41]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(a1)
print(a2)
print(np.intersect1d(a1,a2))

[1 6 5 5 1 7 2 1 3 5]
[5 6 3 3 4 2 1 0 8 2]
[1 2 3 5 6]


如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [42]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

Back to sanity

In [43]:
_ = np.seterr(**defaults)

另一个等价的方式，使用上下文管理器

In [44]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

下面的表达式是正确的吗?
np.sqrt(-1) == np.emath.sqrt(-1)

In [45]:
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Users\pc\AppData\Local\Temp\ipykernel_29372\3357785714.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

如何得到昨天，今天，明天的日期?

In [47]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2024-01-03
2024-01-04
2024-01-05


如何得到所有与2016年7月对应的日期？

In [48]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')  # 日期格式必须是这样的 2016-07    不能是2016-7   2016-07-01  2016-07-1   2016-7-01  2016-7-1 这些都不行   2016-07-01这种格式可以    2016-7-01这种格式不行  2016-07-1这种格式不行    2016-7-1这种格式不行  2016-07-01 00:00:00这种格式不行   2016-7-1 00:00:00这种格式不行 2016-07-01 00:00:00.000000这种格式不行  2016-7-1 00:00:00.000000这种格式不行    2016-07-01 00:00:00.000000000这种格式不行  2016-7-1 00:00:00.000000000这种格式不行  2016-07-01 00:00:00.00000000000000000
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


如何直接在位计算(A+B)\*(-A/2)(不建立中间变量)?

In [50]:
a = np.ones(3)*1
b = np.ones(3)*2
c = np.ones(3)*3
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
print(a)

[-1.5 -1.5 -1.5]


用五种不同的方法去提取一个随机数组的整数部分

In [51]:
a = np.random.uniform(0,10,10)
print(a)
print(a-a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[4.93432633 1.42843384 0.57426803 0.51489421 9.08396204 3.44892553
 2.28959692 3.67679066 2.91199421 6.87227594]
[4. 1. 0. 0. 9. 3. 2. 3. 2. 6.]
[4. 1. 0. 0. 9. 3. 2. 3. 2. 6.]
[4. 1. 0. 0. 9. 3. 2. 3. 2. 6.]
[4 1 0 0 9 3 2 3 2 6]
[4. 1. 0. 0. 9. 3. 2. 3. 2. 6.]


创建一个5*5的矩阵，其中每行的数值范围从0到4

In [52]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


如何用一个生成10个整数的函数来构建数组？

In [53]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


创建一个长度为10的向量，值域为0到1，不包括0和1

In [54]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


创建一个长度为10的随机向量，并排序

In [55]:
a=np.random.random(10)
a.sort()
print(a)

[0.06173743 0.31179363 0.31448625 0.34874775 0.4045858  0.63775893
 0.69014309 0.76472745 0.92201337 0.9763816 ]


对于一个小数组，如何用比 np.sum更快的方式对其求和？


In [56]:
a = np.arange(10)
np.add.reduce(a)


45

np.add.reduce是numpy.add模块中的一个函数，它的作用是对数组中的元素进行累加操作，即返回一个数组所有元素的和。


对于两个随机数组A和B，检查它们是否相等

In [57]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)

False


创建一个只读数组(read-only)

In [58]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

将笛卡尔坐标下的一个10*2的矩阵转换为极坐标形式


In [59]:
a = np.random.random((10,2))
x,y = a[:,0], a[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x) #arctan2(y,x)是求y/x的反正切值，返回值的范围是[-pi,pi]
print(r)
print(t)

[1.05670625 0.62901323 0.41732934 0.62129503 0.96190686 0.87853043
 0.6135099  0.98372528 1.17365459 0.69973345]
[0.62648885 0.60866067 1.53987258 0.69070185 1.17681426 0.46711373
 0.08918736 0.69032398 0.8860678  0.36560124]


创建一个长度为10的向量，并将向量中最大值替换为0

In [60]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.         0.08973939 0.46878546 0.69975978 0.70731401 0.61829126
 0.27613406 0.90673054 0.51439782 0.39424871]


创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域

In [61]:
a = np.zeros((5,5), [('x',float),('y',float)])
print(a)
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [62]:
x = np.arange(8)
y = x + 0.5
c= 1.0 / np.subtract.outer(x,y)
print(c)
print(np.linalg.det(c)) 

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.163637117973


打印每个numpy标量类型的最小值和最大值？

In [63]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


如何打印一个数组中的所有数值?

In [65]:
#np.set_printoptions(threshold=np.nan)
a = np.zeros((16,16))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


给定标量时，如何找到数组中最接近标量的值？

In [66]:
a = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(a-v)).argmin()
print(a[index])

25


思考形状如(100,2)的随机向量，求出点与点的距离
提示：np.atleast_2d, T, np.sqrt

In [67]:
a = np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.58040718 0.01307117 ... 0.60362801 0.6979324  0.5561549 ]
 [0.58040718 0.         0.57059013 ... 0.45335117 0.12950576 0.34496026]
 [0.01307117 0.57059013 0.         ... 0.59059071 0.68888173 0.54314843]
 ...
 [0.60362801 0.45335117 0.59059071 ... 0.         0.55535655 0.10902126]
 [0.6979324  0.12950576 0.68888173 ... 0.55535655 0.         0.45063233]
 [0.5561549  0.34496026 0.54314843 ... 0.10902126 0.45063233 0.        ]]


使用Scipy库更加快速的计算

In [68]:
import scipy.spatial

In [69]:
d = scipy.spatial.distance.cdist(a,a)
print(d)

[[0.         0.58040718 0.01307117 ... 0.60362801 0.6979324  0.5561549 ]
 [0.58040718 0.         0.57059013 ... 0.45335117 0.12950576 0.34496026]
 [0.01307117 0.57059013 0.         ... 0.59059071 0.68888173 0.54314843]
 ...
 [0.60362801 0.45335117 0.59059071 ... 0.         0.55535655 0.10902126]
 [0.6979324  0.12950576 0.68888173 ... 0.55535655 0.         0.45063233]
 [0.5561549  0.34496026 0.54314843 ... 0.10902126 0.45063233 0.        ]]


如何将一个32位的浮点数(float)转换为对应的整数(integer)?

In [70]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32, copy=False)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


如何读取以下文件？

In [71]:
z=np.genfromtxt("missing.dat",delimiter=",")
print(z)

FileNotFoundError: missing.dat not found.

numpy数组枚举(enumerate)的等价操作


In [72]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


构建一个二维高斯矩阵

In [73]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0