1、第一个练习题
Import the numpy package under the name np

In [1]:
import numpy as np

2、打印numpy的版本和配置说明
Print the numpy version and the configuration


In [2]:
print(np.__version__)
print(np.show_config())

1.26.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2628220032720
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.3
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.7
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


3、创建一个长度为10的空向量
Create a null vector of size 10

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4、如何找到任何一个数组的内存大小？
How to find the memory size of any array

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5、如何从命令行得到numpy中add函数的说明文档？
How to get the documentation of the numpy add function from the command line?

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6、创建一个长度为10并且除了第五个值为1的空向量
Create a null vector of size 10 but the fifth value which is 1

In [9]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7、创建一个值域范围从10到49的向量
Create a vector with values ranging from 10 to 49

In [10]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8、反转一个向量（第一个元素变为最后一个）
Reverse a vector (first element becomes last)

In [11]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9、创建一个 3x3 并且值从0到8的矩阵
Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
Z = np.arange(9).reshape(3,3)
print(Z)    

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10、找到数组[1,2,0,0,4,0]中非0元素的位置索引
Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11、创建一个 3x3 的单位矩阵
Create a 3x3 identity matrix

In [14]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12、创建一个 3x3x3的随机数组
Create a 3x3x3 array with random values

In [15]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.16439793 0.74098635 0.64148834]
  [0.7086287  0.6990867  0.68394322]
  [0.64793924 0.49618518 0.28145432]]

 [[0.36533429 0.78591791 0.08454797]
  [0.21048565 0.05685744 0.366874  ]
  [0.01117033 0.98880973 0.18786354]]

 [[0.97681962 0.9473831  0.11073802]
  [0.25436919 0.34246229 0.65772318]
  [0.42725607 0.78911408 0.57506478]]]


13、创建一个 10x10 的随机数组并找到它的最大值和最小值
Create a 10x10 array with random values and find the minimum and maximum values

In [16]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.013116676452693765 0.9909415873359648


14、创建一个长度为30的随机向量并找到它的平均值
Create a random vector of size 30 and find the mean value

In [17]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.48137462199473724


15、创建一个二维数组，其中边界值为1，其余值为0
Create a 2d array with 1 on the border and 0 inside


In [18]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0   
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16、对于一个存在在数组，如何添加一个用0填充的边界？
How to add a border (filled with 0's) around an existing array?
numpy.pad(array, pad_width, mode='constant', constant_values=0)
array: 要填充的数组。
pad_width: 每个轴两侧要填充的宽度。可以是一个整数，表示每个轴两侧填充相同的宽度，也可以是一个长度为 (n, m) 的元组，其中 n 表示数组的维度，m 表示每个轴两侧的填充宽度。
mode: 填充模式，默认是 'constant'。其他常见的填充模式包括 'edge'、'linear_ramp' 等。
constant_values: 在 'constant' 填充模式下使用的常数值，默认为 0。

In [19]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17、以下表达式运行的结果分别是什么？
What is the result of the following expression?

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18、创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=1):k=1表示对角线的上一行

In [23]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


19、创建一个8x8 的矩阵，并且设置成棋盘样式
Create a 8x8 matrix and fill it with a checkerboard pattern
1::2：这是对数组的第一个维度（行）进行切片，从索引 1 开始，以步长为 2 进行切片。这意味着选择数组中的每隔一个元素的行，从第二行开始。
::2：这是对数组的第二个维度（列）进行切片，以步长为 2 进行切片。这意味着选择每隔一个元素的列。

In [24]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20、考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么？
Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index 是 NumPy 中的一个函数，用于将扁平索引（一维索引）转换为多维索引。
扁平索引的计算遵循按照数组形状展开的顺序。在这个例子中，第一个维度 (6) 中的元素有 6 个，第二个维度 (7) 中的元素有 7 个，第三个维度 (8) 中的元素有 8 个。因此，扁平索引 100 对应的多维索引可以计算为：

第一个维度：100 // (7 * 8) = 1
第二个维度：(100 % (7 * 8)) // 8 = 5
第三个维度：(100 % (7 * 8)) % 8 = 4
所以，np.unravel_index(100, (6, 7, 8)) 的结果是 (1, 5, 4)

In [25]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21、用tile函数去创建一个 8x8的棋盘样式矩阵
Create a checkerboard 8x8 matrix using the tile function
numpy.tile(A, reps)
np.tile 是 NumPy 中用于复制数组的函数。它的主要作用是沿指定的轴向复制数组。A: 要复制的数组。
reps: 每个维度上复制的次数。可以是一个整数，表示在每个维度上都复制相同的次数；也可以是一个元组，其中每个元素表示在相应的维度上复制的次数。

In [26]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
